### PR TITLE
added goals to README.md

### PR DESCRIPTION
**Pull request by jakefroeb**
added goals to readme

git fetch -all
git checkout jhf-first-look

### CODE REVIEW

**Review by notdanross — APPROVED** [review]
Thanks for adding the goals!

**Comment by jakefroeb** [comment]
added stretch goals as well

**Comment by jakefroeb** [comment]
added wireframe

**Review by yasmeencole — APPROVED** [review]

**Review by notdanross — APPROVED** [review]
Thanks for adding the goals!

I was able to view the wireframe too.

**Review by emilycentko — APPROVED** [review]

**Pull request merged**
